name: Update and Copy Files

on:
  push:
    branches:
      - main

jobs:
  update-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Update MiSTer_SAM.ini
        run: |
          cp MiSTer_SAM.ini .MiSTer_SAM/MiSTer_SAM.default.ini

      - name: Commit and push update to main
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update MiSTer_SAM.ini"
          git push

  copy-to-updateall:
    needs: update-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout updateall branch
        uses: actions/checkout@v2
        with:
          ref: updateall
          fetch-depth: 0

      - name: Delete all files in Scripts folder
        run: |
          rm -rf Scripts

      - name: Checkout main branch with updated files
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: Copy Files to Scripts subfolder
        run: |
          mkdir -p Scripts
          cp -r main/* Scripts/
          rm -rf main

      - name: Commit changes to updateall
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Copy updated files from main to updateall"
          git push origin updateall
