name: Build update-all db

on:
  push:
    branches:
      - main

jobs:
  build_db:
    runs-on: ubuntu-22.04

    steps:
    - name: Install apt-get utilities
      run: sudo apt-get install detox sharutils

    - uses: actions/checkout@v2
      with:
        ref: main
        path: main
        
    - name: Copy Files to Scripts subfolder
      run: |
        mkdir -p Scripts
        rsync -av --exclude ".git" --exclude ".github" --exclude "readme.md" --exclude "tools-extras" main/ Scripts/
        rm -rf main
  

    - name: Build Custom Database for MiSTer Downloader
      run: set -o pipefail && curl --fail --location https://raw.githubusercontent.com/theypsilon/Downloader_DB-Template_MiSTer/main/.github/build_db.py | python3 -
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
